### ISSUE TITLE
Quality is not accurate when ingame

### ISSUE THREAD

**Issue by tamaster92** [thommcgrath/Beacon-For-Ark#2] opened 2016-09-20 20:10 UTC
When the loot tables are put ingame the quality that spawns is often higher (by a lot) than what is on the program.

Example, I have torches in white drops to spawn apprentice to journeyman. Opened a drop and got a ascendant torch with 234 damage

I am playing on the center, would this effect it?

**Comment by thommcgrath** [comment] 2016-09-22 14:36
These numbers are still very much a mystery to the community, we're working on deciphering the game's mechanics.

The issue is that loot sources have a built-in quality multiplier. So an item quality of 2 in a white beacon is different from an item quality 2 in a red beacon. For The Island and The Center, I believe we've figured these numbers out, so what you're seeing **is** a bit strange. There is some amount of randomness to quality as well. Using cheats to spawn items, the same numeric quality value can produce wildly different results.

So while you're not wrong that this is an issue, at the moment, we (as a community) don't have enough information to really get this right. We're testing though and I'll keep tuning these numbers as much as I can. I've also reached out to Wildcard for some information, but it's been a few days without a response. At this point, I don't think we'll get any help from them.

**Comment by tamaster92** [comment] 2016-09-22 14:44
Is there anyway to limit quality still? Because we do NOT want that high quality items. Also for some reason in some of the higher quality drops I cannot make the item quality lower that apprentice or even journeyman sometimes

**Comment by thommcgrath** [comment] 2016-09-22 15:05
No, it's just the way the game works. The formula for selecting an item's quality is something like:

Minimum = Loot Source Multiplier * Item Min * Random Value
Maximum = Loot Source Multiplier * Item Max * Random Value

It's because of the "Random Value" that items can spawn higher than the defined maximum. I don't know why Wildcard decided that should be there, but it is. I'll make another pass at determining good quality values though.

As for the minimums, that was a bug. I fixed it a few days ago, but a new build has not been released yet.

https://github.com/thommcgrath/Beacon-For-Ark/commit/723621584320552e5424be3d8a892574b4ba31b7

Qualities sometimes need to be less than 1 and my code wasn't allowing that.

**Comment by tamaster92** [comment] 2016-09-22 15:17
Hope the release is soon then :)

Thanks for the help

**Comment by tamaster92** [comment] 2016-09-26 13:05
Could you make a release with that fix in it please? Getting desperate now :/

**Comment by thommcgrath** [comment] 2016-09-26 15:42
I'll try to get it done soon. Got one more major issue I want to tackle first. There's a discussion on Reddit.

**Comment by thommcgrath** [comment] 2016-09-26 15:43
https://www.reddit.com/r/playark/comments/54iklb/beacon_config_chance_to_be_blueprint_doesnt_make/

**Comment by thommcgrath** [comment] 2016-10-07 21:09
I'm going to close this now. I've been playing with quality values produced by A3 for a couple weeks now, and they feel pretty close. Just found the hidden multipliers that were apparently extracted from the source by a modder, so I think this is as close as I'm going to be able to get them.

**Closed by thommcgrath** 2016-10-07 21:09 UTC
